// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc151.DeepSpace2019.subsystems;


import org.usfirst.frc151.DeepSpace2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import org.usfirst.frc151.DeepSpace2019.*;

/**
 *
 */
public class Cargo extends Subsystem {

    
        SpeedController left = null;

        SpeedController right = null;
    
    
        
    
        // Put methods for controlling this subsystem
    
        // here. Call these from Commands.
    
        
    
        public Cargo( ) {
    
            left = new Talon(RobotMap.CARGO_LEFT_WHEEL);
    
            right = new Talon(RobotMap.CARGO_RIGHT_WHEEL);
    
            right.setInverted(true);
    
        }
    
        
    
    
    
        public void initDefaultCommand() {
    
            // Set the default command for a subsystem here.
    
        }
    
        
    
        public void spinWheelsTeleop() {
    
            double forwardSpeed = Robot.oi.getJoystick().getRawAxis(2);
    
            double reverseSpeed = Robot.oi.getJoystick().getRawAxis(3);
    
            left.set(forwardSpeed - reverseSpeed);
    
            right.set(forwardSpeed - reverseSpeed);
    
        }
    
        
    
        public void spinWheelsAuto(double speed) {
    
            left.set(speed);
    
            right.set(speed);
    
        }
    
    }